### PR TITLE
Showing Terraform outputs as "global" variables

### PR DESCRIPTION
**Pull request by lazartravica**
Outputs specified in the Terraform file are passed to the Ansible dynamic inventory JSON accessible to all hosts.

### CODE REVIEW

**Comment by adammck** [comment]
Good idea, thanks for submitting this. Would you mind adding a test case to `parser_test.go`? (I know it's strange that all of the tests are in there; I intend to split them up.) I'd like to be sure that I understand what's going on here.

**Comment by lazartravica** [comment]
Hey @adammck , I've commited the parser test.

**Comment by lazartravica** [comment]
@adammck Fixed the compatibility issue with the #31, able to merge :+1:

**Comment by adammck** [comment]
Looks good to me:

```
adammck@imac5k [git df49397] 
~/code/src/github.com/lazartravica/terraform-inventory$ TF_STATE=fixtures/example.tfstate terraform-inventory --list | jq .
{
  "all": {
    "datacenter": "mydc"
  },
  "alpha": [
    "52.90.134.71",
    "52.90.154.150"
  ],
  "alpha.0": [
    "52.90.134.71"
  ],
  "alpha.1": [
    "52.90.154.150"
  ],
  "beta": [
    "52.23.224.202"
  ],
  "beta.0": [
    "52.23.224.202"
  ],
  "gamma": [
    "198.211.99.194"
  ],
  "gamma.0": [
    "198.211.99.194"
  ],
  "role_web": [
    "52.90.134.71",
    "52.90.154.150"
  ],
  "role_worker": [
    "52.23.224.202"
  ],
  "type_aws_instance": [
    "52.90.134.71",
    "52.90.154.150",
    "52.23.224.202"
  ],
  "type_digitalocean_droplet": [
    "198.211.99.194"
  ]
}
```

This is fantastic, thank you!

**Pull request merged**
