### PR TITLE
Adding better support for groups via the metadata.groups attribute

### LINKED ISSUE #16: Ansible HostGroup Support
At present there doesn't appear to be a way to output the data from terraform as Ansible Host Groups to allow for multiple hosts to be configured via a single play.

For example, a play that starts with "hosts: webservers" doesn't know that "aws_instance.webserver.0" should belong to the "webservers" ansible group.

It would be nice to have some way of mapping aws_instance.webserver.* to a group or similar.

### PR DESCRIPTION
**Pull request by jackspirou**
This pull request adds better support for groups, via the `metadata.groups` attribute and fixes #16

### CODE REVIEW

**Comment by vasiliyb** [comment]
@jackspirou I've tried compiling from your branch, with no avail:

```
go get github.com/jackspirou/terraform-inventory
cd src/gitub.com/jackspirou/terraform-inventory
go build
```

./terraform-inventory --list still shows the hosts separate

**Comment by jackspirou** [comment]
@vasiliyb can you send me an example file your using? Do you have a `metadata.groups` attribute listed?

**Comment by vasiliyb** [comment]
@jackspirou email sent, thank you!  I dont see metadata.groups in --list output

**Comment by adammck** [comment]
Hello! Thanks very much for your patch. However, I also can't seem to get it to work. None of the resources in my state files seem to include a `meta.groups` attribute. Can you provide an example?

**Comment by jackspirou** [comment]
Hi @vasiliyb and @adammck, sorry for the delay in responding.  So the reason I submitted this was because our team needed something that Ansible groups could easily pickup.  This PR takes the approach of adding a `metadata.groups` attribute (which I hear is quite popular with other tools) to the `.tfstate` file.  This can be done by including the following code for a `resource` in `main.tf`

```HCL
resource "openstack_compute_instance_v2" "hive" {
  count = "${lookup(var.instances, var.env)}"
  security_groups = ["default", "HTTP"]
  name = "${var.env}-hive-${count.index}"
  region = "${var.region}"
  image_name = "${module.settings.images}"
  flavor_name = "${lookup(var.flavor, var.env)}"
  key_pair = "${module.settings.key_pair}"
  floating_ip = "${lookup(var.static_address, var.env)}"
  network {
    name = "${module.settings.private_net}"
  }
  metadata {
    groups = "web,api,hive"
  }
}
```

After using `terraform apply` with the example above, running `terraform-inventory --list <filepath>` would result in: 

```JSON
{"api":["10.65.82.170"],"hive":["10.65.82.170"],"web":["10.65.82.170"]}
```

Let me know your thoughts and if this still makes sense given PR #22.

**Comment by jackspirou** [comment]
After taking a look at PR #22 I think it accomplishes much of this, but from what I understand it doesn't allow for multiple resources to one group, or multiple resources to multiple groups. So for example, if you had a shared Ansible bootstrap play to set default configuration on all servers belonging to the HTTP Ansible group this might become an issue.

Again all feedback welcome.

**Comment by adammck** [comment]
Thanks for getting back to me, @jackspirou. You're right that #22 doesn't provide arbitrary group names, which is something I'd very much like to add. I wasn't familiar with the metadata attribute, because (as far as I can tell), it's only supported by [the OpenStack provider](https://terraform.io/docs/providers/openstack/r/compute_instance_v2.html#metadata). But most other providers have their own mechanism (e.g. AWS's instance tags) for this sort of thing.

I refactored master a bit already (to make this sort of thing simpler in future), and will try to get this merged shortly. Thanks very much for the patch!

**Comment by jackspirou** [comment]
This PR has conflicts.  Closing.

**Pull request closed without merging**
