### PR TITLE
Ordered output for Terraform resources with 'count'

### PR DESCRIPTION
**Pull request by SamiHiltunen**
Hey,

First of, thanks for the tool! It makes using Ansible with Terraform very convenient. 

This PR sorts the output groups that correlate to Terraform resources created with ```count```. 

As an example, check this old generated inventory. The ```kafka``` list is not ordered a in the same manner as it is in Terraform.
```json 
...
"kafka":  ["kafka1", "kafka3", "kafka2"],
"kafka.0": "xxx.xxx.xxx.xxx",
"kafka.1": "yyy.yyy.yyy.yyy",
"kafka.2": "zzz.zzz.zzz.zzz",
...
```

After this PR, the output of ```kafka``` list will be in proper order:

```json 
...
"kafka":  ["kafka1", "kafka2", "kafka3"],
"kafka.0": "xxx.xxx.xxx.xxx",
"kafka.1": "yyy.yyy.yyy.yyy",
"kafka.2": "zzz.zzz.zzz.zzz",
...
```

As an aside, it will print to standard error when a key is overwritten during resource gathering. The tool has an issue, where resources of different types will overwrite others with the same name. Also, having tags with same value as the name of a resource will overwrite the old value. As it is not solvable in a backwards compatible manner, I decided to just print this out so the users will at least see the errors.

### CODE REVIEW

**Comment by adammck** [comment]
Thanks, this looks like a very sensible change. I'll try to get it reviewed in the next couple of days. Could you rebase against master, to ensure that it works with #72?

**Comment by SamiHiltunen** [comment]
Hey, I've rebased on master and the tests are passing.

**Comment by Dwaynekj** [comment]
This would also be useful for me

**Comment by SamiHiltunen** [comment]
Polite ping! Would it be possible to have this merged?

**Comment by adammck** [comment]
Thanks very much for this! Sorry about the delay on reviewing it.

**Comment by Dwaynekj** [comment]
Awesome! @adammck When do you think another official release will be packaged?

**Pull request merged**
