### PR TITLE
Workaround for multiple use of a module resulting in duplicate keys

### PR DESCRIPTION
**Pull request by AndiDog**
Code change has an example for when this workaround applies. Otherwise, you'd get errors like "overwriting already existing individual key host.0, old: [10.101.117.202], new: 10.101.95.119" because all instantiations of a module would be in the same namespace without prefixing or altering the key.

Also, this ignores keys like `data.aws_ami.freebsd_with_zfs` because they don't represent hosts. This way, I could remove the TODO entry and actually print a warning in all other cases where the regex fails to parse the resource key.

### CODE REVIEW

**Comment by queglay** [comment]
I just encountered this error - overwriting already existing individual key openvpnip.0, old: [13.205.55.116], new: 52.13.99.26[all]

when you say the problem occurs with multiple use of a module, what do you mean? do you mean if a role is implemented more than once? or do you mean multiple use of a terraform module?

**Comment by AndiDog** [comment]
I have something like this (simplified):

```
module "server1" {
  source = "./modules/freebsd-ec2-instance"
  name   = "server1"
}

module "server2" {
  source = "./modules/freebsd-ec2-instance"
  name   = "server2"
```

and the module reads like this:

```
variable "name" {}
resource "aws_instance" "host" {
  # ...

  tags {
    Name = "${var.name}"
  }
}
```

Since you can't dynamically name the resource (`"${var.name}"` instead of `"host"`), this patch fixes the ambiguity of both module instantiations producing a resource called "host".

**Comment by AndiDog** [comment]
Can we merge this? It would help implement #113 (which I'm working on as well).

**Comment by AndiDog** [comment]
Will supersede with my PR for supporting Terraform 0.12

**Pull request closed without merging**
