### PR TITLE
add tags/groups support for gcp

### PR DESCRIPTION
**Pull request by stephansnyt**

### CODE REVIEW

**Comment by adammck** [comment]
Hello, @stephansnyt! This looks good to me, but can we get a test in [parser_test.go](https://github.com/adammck/terraform-inventory/blob/master/parser_test.go#L12)? Should just be a matter of adding an example to the giant fixture and the expected output.

**Comment by mblarsen** [comment]
@stephansnyt could you add `digitalocean_droplet` to the case? Then it will work on digital ocean tags as well.

```
case "digitalocean_droplet", "google_compute_instance":
```

To the test you can add these tags to the existing digitalocean_droplet:

```
"tags.#": "2",
"tags.1": "staging",
"tags.2": "webserver"
```

.. and this at the and of the expected output:

```
	"webserver": ["192.168.0.3"],
	"staging": ["192.168.0.3"]
```

(Remember to put a comma efter the previous value.)

I tested your change with `digitalocean_droplet` change on top of it as well as with the above test fixtures and it all went well :)

Thanks

**Comment by mblarsen** [comment]
@stephansnyt @adammck Any change this could be merged? I'll gladly make a PR that includes both providers + tests.

**Comment by yanc0** [comment]
I have created a PR on the @stephansnyt 's master branch. Hope He'll accept it and then we can merge this PR. For DO, maybe we can create its own PR for tracking purposes? What do you think @mblarsen?

Thanks

**Comment by mblarsen** [comment]
That's great @yanc0 — I can add the DO parts as soon as this is merged. But both @stephansnyt and @adammck seems to be really busy, crossing fingers for near-future merge :)

**Comment by adammck** [comment]
Merged the feature and tests in #55. Thanks!

**Pull request closed without merging**
